In [1]:
import pandas as pd

import src
from src.load import DataLoader

In [2]:
pd.set_option("display.max_rows", 1024)
pd.set_option("display.max_colwidth", 256)

In [3]:
dl = DataLoader()

In [4]:
videos = (
    dl.videos(filtered=True)
    .join(dl.channels(), "channel_id")
    .select(
        ["video_id", "channel", "video_likes", "video_views", "video_uploadtime", "video_title"],
    )
    .to_pandas()
)

sents = dl.sentences(filtered=True).join(dl.popbert(filtered=True), "sentence_id").to_pandas()

sents = sents.groupby("video_id", observed=True).agg(
    n_sentences=("video_id", "size"),
    elite=("elite", "mean"),
    pplcentr=("pplcentr", "mean"),
)

videos = videos.merge(sents, on="video_id")

# Most Liked

In [5]:
top_like_videos = videos[videos.channel != "FDP"]

quantiles = top_like_videos.groupby("channel").video_likes.quantile(q=0.99).rename("quantile")

In [6]:
df = top_like_videos.merge(quantiles, how="left", on="channel")
df["top_1p"] = df.apply(lambda x: 1 if x.video_likes > x["quantile"] else 0, axis=1)

In [7]:
top_videos = (
    df.sort_values(["channel", "video_likes"], ascending=False)
    .groupby("channel")
    .head(
        10,
    )
    .set_index(["channel", "video_id"])
)

In [8]:
top_videos

                     video_likes  video_views video_uploadtime  \
channel video_id
SPD     HxtUEy0aY_U         7048       261702       2019-05-24
        J5_6XjAEKWo         3215       124091       2019-12-06
        Y8JWqzIEkYg         2943       562534       2021-08-04
        R-Td0654RxU         1852       116863       2021-05-11
        qcear4-NAG8         1200        38404       2020-12-12
        4K5BGB34i_k          711       172277       2021-09-21
        84DhwYfXY7c          619        19731       2021-12-31
        J7WJ8UrUwJM          607        10036       2021-05-09
        jvrswEl5WRY          500        49390       2023-02-08
        aZx04PRQUb8          426         8247       2019-11-16
Left    xJ2_ykd3qQg        19970       769998       2018-02-22
        thsWrPlTCHU        15777       663977       2018-11-30
        35yCb1A9bmc         6428       230089       2019-11-07
        j_AS5WOaylM         4402       149768       2021-05-10
        Vdtfq7uwrjE         3469       312521       2021-08-28
        1gGx4mIOwtQ         3117       137967       2019-12-05
        L3BWY8CWjjE         2396       303424       2021-09-12
        j-GoyDi0NUA         1702       208320       2019-04-22
        l5abgjJlcE4         1692        37786       2023-05-09
        p41mETuQQ-E         1496        39602       2021-02-27
Greens  Em_WUdK5WKI        12171       970937       2021-08-24
        JVK9a9YAG1A          801        14152       2021-09-08
        8onMba916cw          709        43383       2022-10-16
        RUew3wECQBU          555        18255       2021-06-12
        ddut9jiggeA          501        38978       2021-09-12
        rMThbJVcY-Y          443         8264       2021-09-17
        smOJuUd4yVA          405        18552       2022-10-14
        5YjaQnY4BP4          394         8118       2021-10-29
        vIGIkZhS258          376         7674       2021-09-19
        3LSpC_z1m_k          373        18603       2020-11-20
CSU     G5CBslnIYbs          429      1374514       2018-09-24
        qV8plOy7mO8          273      1180669       2023-09-10
        toVAryo-KIA          216         4520       2019-09-30
        K0HX5OUY1cQ          172         3809       2019-11-20
        pDyf3tu6_GQ          144         8304       2018-09-15
        RKUU8D_Louc          102         3589       2020-09-11
        KuUwqsw86Wk          100         7053       2021-02-17
        -YMkFuGjPr4           99         4187       2021-08-31
        DryIeBFXz00           97        20314       2019-04-18
        IHmPYYkwsVE           96         6316       2019-10-17
CDU     W71tUlrMeD4         3272      1366292       2021-08-22
        kRgig-3p8J4         2672       180064       2023-07-27
        TzGjX2K5na4         2454          946       2021-08-30
        LrHKojPL7uU         2275         1441       2021-09-05
        TtmRKq_k4_k         1557        95204       2021-09-18
        QYfn1To3S0g         1444       212612       2021-01-16
        MmnbRfL87yE          757        69953       2023-02-16
        gt4XjbdkV6k          666        53562       2023-04-26
        CrOVe9BhHAM          655       271192       2021-09-20
        B59WbE0OvGA          606        38902       2023-12-22
AfD TV  9-KekzU3AJU       114061      2708077       2023-06-22
        qpGQ-l5o5Js        42502       492150       2021-11-24
        N0R_bAITYBA        34632       494284       2023-11-28
        FqZ8eKFJZU4        31729       401182       2022-03-07
        sVgZHsnWqrE        29602       606412       2022-11-23
        W-gBgUkLHAI        27685       328410       2021-12-15
        S4-ZdKHSAr8        26691       644321       2019-05-04
        UwAlL_3QU18        26557       337452       2023-06-06
        1pksqcM2TBI        25903       490639       2022-02-18
        CedyRmtIrxc        25573       318324       2022-11-12
AfD BT  dT27FAzrKXE       128160      2195987       2022-09-07
        W-SL9CAaOmc        71742      2086875       2022-11-23
        QpZd_pYnIDo        67392      1134478       2023-06-23
        SfPCPNepf6o        64441      1626433       2022-12-02
        2ImCFvfWkdk        63035      1140949       2023-02-08
        6StYs4xB_bc        62360      1505295       2023-09-06
        eP_gnjZUR6I        61934       828456       2020-12-09
        o3VTykBOsgs        60915       789019       2021-09-07
        XZYA59B5gwo        57537      1731963       2023-01-19
        vNBO8U45OxI        53935       697427       2022-03-17

                                                                                                              video_title  \
channel video_id
SPD     HxtUEy0aY_U                             Reaktion auf Rezo Statement | Lars Klingbeil, Tiemo Wölken, Kevin Kühnert
        J5_6XjAEKWo                                                                                Rede von Kevin Kühnert
        Y8JWqzIEkYg                                                Was ist eigentlich alles drin, wenn man die SPD wählt?
        R-Td0654RxU                                                          Respekt für Dich. Kompetenz für Deutschland.
        qcear4-NAG8                                                                              Soziale Politik für Dich
        4K5BGB34i_k                                                         Weil es nicht egal ist, wer das Land regiert.
        84DhwYfXY7c                                          Neujahrsansprache von Kanzler Scholz | Jahreswechsel 2021/22
        J7WJ8UrUwJM                                                                         „Auf den Kanzler kommt es an“
        jvrswEl5WRY                    Büttenrede von Lars Klingbeil beim Orden wider den tierischen Ernst 2023 in Aachen
        aZx04PRQUb8                                     Jetzt abstimmen! Saskia Esken & Norbert Walter-Borjans zum Finale
Left    xJ2_ykd3qQg                    Caren Lay nimmt die AfD-Männer auseinander, die angeblich Frauenrechte verteidigen
        thsWrPlTCHU                                     Stefan Liebich zerpflückt die Fakenews der AfD zum Migrationspakt
        35yCb1A9bmc                          Janine Wissler (DIE LINKE): Nachhilfe für die AfD in Sachen Meinungsfreiheit
        j_AS5WOaylM                                                                        Macht das Land gerecht. Jetzt.
        Vdtfq7uwrjE       16 Jahre: Genug Zeit verloren.  Machen wir das Land gerecht. - Wahlspot zur Bundestagswahl 2021
        1gGx4mIOwtQ                                       Gysi & Wissler: Die DDR, Marx und der Demokratische Sozialismus
        L3BWY8CWjjE                                     Wahlspot DIE LINKE: Gemeinsam machen wir das Land gerecht. JETZT.
        j-GoyDi0NUA                      DIE LINKE: Für ein solidarisches Europa! Unser Wahlwerbespot zur Europawahl 2019
        l5abgjJlcE4                                      Martin Schirdewan: "Wer Europa will muss es den Reichen nehmen!"
        p41mETuQQ-E                                                                         Der LINKE Internationale-Chor
Greens  Em_WUdK5WKI                                                Ein schöner Land – Grüner Spot zur Bundestagswahl 2021
        JVK9a9YAG1A                                                   Auf dem Weg mit Martin Rütter und Annalena Baerbock
        8onMba916cw                                              Luisa Neubauer | Rede auf dem Parteitag in Bonn | #BDK22
        RUew3wECQBU                                            Annalena Baerbock | Rede auf dem Bundesparteitag | #dBDK21
        ddut9jiggeA                                               Auf dem Weg mit Judith Holofernes und Annalena Baerbock
        rMThbJVcY-Y                                                    Auf dem Weg mit Claudia Roth und Annalena Baerbock
        smOJuUd4yVA                                               Robert Habeck | Rede auf dem Parteitag in Bonn | #BDK22
        5YjaQnY4BP4                                                 Koalitionsgespräche Woche 01: Sondieren und Koalieren
        vIGIkZhS258                                                           Robert Habeck | Rede auf dem #Wahlparteitag
        3LSpC_z1m_k                                                       Politische Rede von Annalena Baerbock | #dbdk20
CSU     G5CBslnIYbs                                                                                         Ja zu Bayern!
        qV8plOy7mO8                                Landtagswahl am 8. Oktober 2023 - Damit Bayern stark und stabil bleibt
        toVAryo-KIA                                                                     Fail des Tages | "Danke, Antifa!"
        K0HX5OUY1cQ                                                 Fail des Tages I Öffentliches Gelöbnis der Bundeswehr
        pDyf3tu6_GQ                                                                                         Ja zu Bayern!
        RKUU8D_Louc                                                                                      Gründung der CSU
        KuUwqsw86Wk                                                                   Best-of Aschermittwoch 2021 #dahoAM
        -YMkFuGjPr4           Alexander Dobrindt spricht Klartext zur Richtungswahl 2021: Starke Mitte oder linkes Chaos?
        DryIeBFXz00                                                                 Manfred Weber - Unser Mann für Europa
        IHmPYYkwsVE                                    EPISODE 2 -"Neue Töne" -der Polit-Podcast der CSU mit Markus Söder
CDU     W71tUlrMeD4                                                                         Deutschland gemeinsam machen.
        kRgig-3p8J4                             Einfach mal machen – Folge #7 mit Anna Schneider und Richard David Precht
        TzGjX2K5na4                                 #Deutschlandreise: Das Reisetagebuch. 26. August 2021: Korschenbroich
        LrHKojPL7uU                  #Deutschlandreise: Das Reisetagebuch. 3. September 2021: Apolda, Eisenach und Erfurt
        TtmRKq_k4_k                                                                           50 Fragen an Philipp Amthor
        QYfn1To3S0g                                                                                  Grußwort Donald Tusk
        MmnbRfL87yE                             EINFACH MAL MACHEN Folge #4 – mit Ulrike Herrmann und Prof. Clemens Fuest
        gt4XjbdkV6k                                  Einfach mal machen – Folge #5 mit Nena Brockhaus und Hendrik Streeck
        CrOVe9BhHAM                     Alles, was wir tun, tun wir aus Verantwortung für unser Land. Und:  #wegenmorgen.
        B59WbE0OvGA                               Einfach mal machen – Folge #11 mit Micky Beisenherz und Robin Alexander
AfD TV  9-KekzU3AJU                          Der Weidel-Hammer: Bei dieser Rede tobte der Bundestag! - AfD - Alice Weidel
        qpGQ-l5o5Js                                              „Diese Maßnahmen sind ein himmelschreiendes Verbrechen!“
        N0R_bAITYBA                        Der Weidel-Hammer im Bundestag: "Was haben Sie da auf unser Volk losgelassen?"
        FqZ8eKFJZU4                                     Das hat gesessen! Martin Hess nimmt hier kein Blatt vor den Mund!
        sVgZHsnWqrE                                           Millionen ohne Berufsabschluss - ein Teil davon sitzt hier!
        W-gBgUkLHAI                                                                       Alice Weidel ZERLEGT die Ampel!
        S4-ZdKHSAr8                                                     ❝Die EU ist Irrsinn!❞ | Alice Weidel in Pforzheim
        UwAlL_3QU18                         Interview im Deutschlandfunk: Tino Chrupalla weist Moderator in die Schranken
        1pksqcM2TBI                                                 Nach Gender-Kritik toben Grüne mit wütendem Geschrei!
        CedyRmtIrxc                                     Lauterbach-Rücktritt statt Isolationspflicht - Alice Weidel - AfD
AfD BT  dT27FAzrKXE      Alice Weidel auf 180! So hat sie noch nie mit der Ampel abgerechnet! - AfD-Fraktion im Bundestag
        W-SL9CAaOmc       Baerbock stinksauer: Markus Frohnmaier entlarvt Doppelmoral der Außenministerin! - AfD-Fraktion
        QpZd_pYnIDo          Migrationsmurks der Ampel bringt Norbert Kleinwächter auf 180! 💥 - AfD-Fraktion im Bundestag
        SfPCPNepf6o                     Beatrix von Storch rechnet mit den Klima-Spinnern ab! - AfD-Fraktion im Bundestag
        2ImCFvfWkdk  Alice Weidel nutzt die Regierungserklärung von Scholz für eine Generalabrechnung mit der Ampel - AfD
        6StYs4xB_bc                                    Stefan Keuter rechnet mit Baerbock ab! - AfD-Fraktion im Bundestag
        eP_gnjZUR6I     Aufruhr im Bundestag, als Alice Weidel mit Merkels Politik abrechnet! - AfD-Fraktion im Bundestag
        o3VTykBOsgs        Aufruhr im Bundestag, als Alice Weidel mit Merkels Regierungspolitik abrechnet! - AfD-Fraktion
        XZYA59B5gwo   Entgleisung von Göring-Eckardt bei Applaus für AfD-Rede! Martin Sichert - AfD-Fraktion im Bundestag
        vNBO8U45OxI  Wer nach dieser Rede noch für die Impfpflicht ist, dem ist nicht mehr zu helfen! - Alice Weidel, AfD

                     n_sentences     elite  pplcentr  quantile  top_1p
channel video_id
SPD     HxtUEy0aY_U           59  0.033898  0.000000    867.48       1
        J5_6XjAEKWo          123  0.024390  0.040650    867.48       1
        Y8JWqzIEkYg            9  0.000000  0.000000    867.48       1
        R-Td0654RxU           10  0.000000  0.200000    867.48       1
        qcear4-NAG8           17  0.117647  0.176471    867.48       1
        4K5BGB34i_k            7  0.000000  0.000000    867.48       0
        84DhwYfXY7c          105  0.000000  0.076190    867.48       0
        J7WJ8UrUwJM          439  0.013667  0.045558    867.48       0
        jvrswEl5WRY          120  0.041667  0.008333    867.48       0
        aZx04PRQUb8           19  0.000000  0.052632    867.48       0
Left    xJ2_ykd3qQg           43  0.255814  0.000000   3370.44       1
        thsWrPlTCHU           76  0.157895  0.000000   3370.44       1
        35yCb1A9bmc           38  0.447368  0.026316   3370.44       1
        j_AS5WOaylM           24  0.000000  0.041667   3370.44       1
        Vdtfq7uwrjE            7  0.000000  0.000000   3370.44       1
        1gGx4mIOwtQ          272  0.033088  0.007353   3370.44       0
        L3BWY8CWjjE           23  0.000000  0.130435   3370.44       0
        j-GoyDi0NUA           17  0.058824  0.058824   3370.44       0
        l5abgjJlcE4           27  0.518519  0.111111   3370.44       0
        p41mETuQQ-E           11  0.000000  0.000000   3370.44       0
Greens  Em_WUdK5WKI           13  0.000000  0.000000    469.68       1
        JVK9a9YAG1A          368  0.016304  0.008152    469.68       1
        8onMba916cw          128  0.093750  0.007812    469.68       1
        RUew3wECQBU          280  0.028571  0.050000    469.68       1
        ddut9jiggeA          362  0.005525  0.013812    469.68       1
        rMThbJVcY-Y          166  0.024096  0.024096    469.68       0
        smOJuUd4yVA          121  0.024793  0.000000    469.68       0
        5YjaQnY4BP4           46  0.000000  0.000000    469.68       0
        vIGIkZhS258          153  0.124183  0.019608    469.68       0
        3LSpC_z1m_k          157  0.025478  0.038217    469.68       0
CSU     G5CBslnIYbs            9  0.000000  0.000000    250.20       1
        qV8plOy7mO8           24  0.000000  0.083333    250.20       1
        toVAryo-KIA           14  0.285714  0.071429    250.20       0
        K0HX5OUY1cQ           10  0.200000  0.100000    250.20       0
        pDyf3tu6_GQ           32  0.093750  0.125000    250.20       0
        RKUU8D_Louc           22  0.000000  0.045455    250.20       0
        KuUwqsw86Wk           34  0.029412  0.000000    250.20       0
        -YMkFuGjPr4           19  0.157895  0.000000    250.20       0
        DryIeBFXz00           24  0.000000  0.166667    250.20       0
        IHmPYYkwsVE          654  0.013761  0.003058    250.20       0
CDU     W71tUlrMeD4           21  0.000000  0.000000    746.08       1
        kRgig-3p8J4          670  0.031343  0.005970    746.08       1
        TzGjX2K5na4           15  0.000000  0.066667    746.08       1
        LrHKojPL7uU           11  0.000000  0.090909    746.08       1
        TtmRKq_k4_k          167  0.011976  0.005988    746.08       1
        QYfn1To3S0g           19  0.052632  0.105263    746.08       1
        MmnbRfL87yE          542  0.029520  0.005535    746.08       1
        gt4XjbdkV6k          602  0.014950  0.003322    746.08       0
        CrOVe9BhHAM           37  0.000000  0.000000    746.08       0
        B59WbE0OvGA          624  0.022436  0.004808    746.08       0
AfD TV  9-KekzU3AJU           61  0.508197  0.065574  22478.33       1
        qpGQ-l5o5Js           57  0.087719  0.035088  22478.33       1
        N0R_bAITYBA           69  0.478261  0.101449  22478.33       1
        FqZ8eKFJZU4           35  0.571429  0.028571  22478.33       1
        sVgZHsnWqrE          103  0.242718  0.019417  22478.33       1
        W-gBgUkLHAI           59  0.661017  0.033898  22478.33       1
        S4-ZdKHSAr8          279  0.125448  0.021505  22478.33       1
        UwAlL_3QU18           42  0.119048  0.000000  22478.33       1
        1pksqcM2TBI           67  0.089552  0.000000  22478.33       1
        CedyRmtIrxc           39  0.230769  0.000000  22478.33       1
AfD BT  dT27FAzrKXE           97  0.432990  0.051546  29149.64       1
        W-SL9CAaOmc           45  0.288889  0.022222  29149.64       1
        QpZd_pYnIDo           85  0.188235  0.105882  29149.64       1
        SfPCPNepf6o           44  0.431818  0.045455  29149.64       1
        2ImCFvfWkdk           72  0.388889  0.000000  29149.64       1
        6StYs4xB_bc           54  0.240741  0.000000  29149.64       1
        eP_gnjZUR6I           76  0.486842  0.052632  29149.64       1
        o3VTykBOsgs           79  0.417722  0.050633  29149.64       1
        XZYA59B5gwo           66  0.318182  0.106061  29149.64       1
        vNBO8U45OxI           38  0.236842  0.000000  29149.64       1

In [9]:
top_videos.reset_index()[["channel", "video_likes", "video_views", "video_title"]].to_csv(
    src.OUT / "tables/most_liked_videos_per_channel.csv",
    index=False,
)

# Most Anti-Elitism

In [10]:
quantiles = videos.groupby("channel").elite.quantile(q=0.99).rename("quantile")

In [11]:
df = videos.merge(quantiles, how="left", on="channel")
df["top_1p"] = df.apply(lambda x: 1 if x.elite > x["quantile"] else 0, axis=1)

In [12]:
top_videos = (
    df.sort_values(["channel", "elite"], ascending=False)
    .groupby("channel")
    .head(
        10,
    )
    .set_index(["channel", "video_id"])
)

In [13]:
top_videos

                     video_likes  video_views video_uploadtime  \
channel video_id
SPD     F0c4_NPpnGA          142         2480       2024-01-18
        d6vy8DvlA6k          177         2811       2020-03-05
        2eJPpGsTI0c          180         2606       2021-08-30
        2rwXzpbyDEU          165         3675       2020-03-05
        y1WnueSc9fQ           61          839       2021-05-18
        3HwEQBSzMUI           32          967       2023-12-09
        B4hGX4jIMks          198         4516       2024-01-12
        CtIAZCMJyWg          144         5122       2022-03-25
        nuVHZu54xvU          111         2109       2021-09-18
        67wvrzYddRo           77          493       2021-08-14
Left    l5abgjJlcE4         1692        37786       2023-05-09
        MUgDgKGu5Bg          431         7201       2021-09-02
        9DC619q6mVA           24          630       2019-04-05
        FFg9z4i9lqM          119         2704       2022-12-06
        35yCb1A9bmc         6428       230089       2019-11-07
        GSfgp8r9h3A           91         2762       2018-06-18
        s15ADZa3BvI          177         2270       2023-09-21
        L3wllg-iZNg          109         1488       2022-11-25
        zN5YQIN5ep8          168         3614       2021-09-20
        quIkOTiaCSA           75          989       2018-09-26
Greens  BKA5Rs9r7WE            5          281       2018-01-27
        iM80OK5_e9E           13          498       2018-01-27
        sTFRFy4jcN4           22         1868       2018-11-10
        fvgOxVAw5hQ            6          212       2018-01-27
        kMlQJQjV__M          194         6922       2019-09-20
        5aAfx-1usQ0           84         1113       2018-06-29
        neJCKmYZZBc           42         1133       2019-11-16
        QO_Y14cx8Lo           51          774       2021-06-13
        _cfV76TxsY8           15         1722       2019-11-16
        YjN_Q4JIQjw           41         2924       2022-10-14
FDP     UYtJ1msQuYM            0          547       2019-12-02
        pdlIAFuKRQI            0         2598       2020-02-14
        4yJCimj2O_U            0          564       2018-01-08
        exvX1gSRtD0            0          567       2019-12-17
        TbTJccB-Up8            0         2333       2020-03-02
        QICTmpFHwmQ            0          812       2019-07-04
        Ie6tihXg7A4            0          825       2019-12-16
        6n0TgxBjWuc            0        41236       2021-07-30
        rDZdmV-4DgI            0         1493       2018-01-08
        1ze5fpz3oFE            0         5300       2019-04-29
CSU     toVAryo-KIA          216         4520       2019-09-30
        nDYYxXPqXGQ           71         5213       2023-02-22
        N431nIgfOnA           21          641       2020-02-05
        K0HX5OUY1cQ          172         3809       2019-11-20
        iPKZDFAdIYs           28          472       2019-10-05
        983lQr9XElg           82         2932       2021-09-16
        16jEAhKmF-I           35          955       2021-09-25
        6eSiwakBcgY           21          323       2021-09-20
        pJVOIfs3h-k           29         2884       2019-03-31
        -YMkFuGjPr4           99         4187       2021-08-31
CDU     EksM0bVVH1M           36         1763       2020-02-05
        bbcjzNNtveo           18          334       2022-01-19
        xgkXD9s4Opc          543        20013       2020-02-26
        oYAl63O10gU           15          693       2019-04-08
        6_RMW7sF4kM           69         2893       2023-06-20
        t9oeOo08rGM            8          190       2022-01-24
        q64peGPwHV8           46          965       2021-09-22
        GfIbnaLOS7M          174         4009       2021-09-08
        mINqf00pBts           18          569       2019-09-13
        lxNdOTGa3-I           27         1480       2021-11-27
AfD TV  wtAo1hE9pEc         1152         7615       2023-06-15
        gbz_LecnBGs        14947       215714       2023-05-15
        NZYZJ85lE2I         7595        64732       2022-06-07
        XdKfTJZeuec         2283        18716       2019-03-28
        3W20MPRKKiM         1815         9195       2023-06-15
        c26W8Kr-3pE         1685        10877       2021-05-29
        W-gBgUkLHAI        27685       328410       2021-12-15
        xHA4qgJFXuw         1982        11341       2023-12-19
        Kz0pA-d8yik         1884        12047       2023-03-17
        -FNThb9JO-w        21098       294811       2020-05-29
AfD BT  bfjB_0uTBAo          492         2469       2020-05-14
        lTU0Ojmf67o        14958       115541       2021-12-15
        VNZxUu862RQ         6548        54253       2019-07-03
        W8xf0eEvVQE        20731       220567       2022-06-08
        uYIlmYDoy1M         7368        70260       2022-06-29
        _p9AyHJTzuw         3686        24741       2023-09-11
        mGLBCRcFQyE         4577        32819       2023-05-26
        otnmHzXujZQ         2165        17033       2020-10-09
        Z5HES8fziQo         3951        31480       2023-06-15
        zbWzxoJklmg         5425        55456       2021-01-13

                                                                                                            video_title  \
channel video_id
SPD     F0c4_NPpnGA                                       Deportations-Wahnsinn: AfD will Millionen Menschen vertreiben
        d6vy8DvlA6k                                                        Mützenich: Die AfD hat sich schuldig gemacht
        2eJPpGsTI0c                                                                               Sven Walser | Wechsel
        2rwXzpbyDEU                                                                  Lambrecht: Das ist widerlich, AfD!
        y1WnueSc9fQ                                                                              Maaßen und Maskenschmu
        3HwEQBSzMUI                                                                Katarina Barley | SPD-Parteitag 2023
        B4hGX4jIMks                                                 Geheimtreffen AfD und Neonazis: Die Lage ist ernst!
        CtIAZCMJyWg                                                        Kevin Kühnert: Entschlossen für Zusammenhalt
        nuVHZu54xvU                                              Christian Gerhaher I "Deswegen wähle ich Olaf Scholz!"
        67wvrzYddRo                                                                        Mario Giordano | Solidarität
Left    l5abgjJlcE4                                    Martin Schirdewan: "Wer Europa will muss es den Reichen nehmen!"
        MUgDgKGu5Bg                                                      Jan Korte spricht Klartext:  Über Lindners FDP
        9DC619q6mVA                                    Martina Michels - Kandidatin zur Europawahl 2019 stellt sich vor
        FFg9z4i9lqM                                       Ein Jahr Ampel-Regierung: Janine Wissler sagt, was Sache ist.
        35yCb1A9bmc                        Janine Wissler (DIE LINKE): Nachhilfe für die AfD in Sachen Meinungsfreiheit
        GSfgp8r9h3A                                    Katja Kipping: Aktuelles Statement zum Streit der Unionsparteien
        s15ADZa3BvI                                    "Das Haus Europa ist eine abgewirtschaftete Bruchbude geworden."
        L3wllg-iZNg                    Bundesrat stimmt über Bürgergeld ab. Ein Schätzung von Katja Kipping (DIE LINKE)
        zN5YQIN5ep8        Gekaufte Politik? Nicht mit uns. Das Wahlprogramm der LINKEN zur Bundestagswahl 2021 erklärt
        quIkOTiaCSA                                            Bezahlbare Miete statt fetter Rendite - Kampagnenauftakt
Greens  BKA5Rs9r7WE                                       Christian Meyer Bewerbungsrede Parteirat Bundesparteitag 2018
        iM80OK5_e9E                                        Toni Hofreiter Bewerbungsrede Parteirat Bundesparteitag 2018
        sTFRFy4jcN4                                                 Sven Giegold: Grüner Spitzenkandidat zur Europawahl
        fvgOxVAw5hQ                                          Katja Dörner Bewerbungsrede Parteirat Bundesparteitag 2018
        kMlQJQjV__M                           Annalena Baerbock & Anton Hofreiter zu den Ergebnissen des Klimakabinetts
        5aAfx-1usQ0                                                                       Ein entscheidendes Wochenende
        neJCKmYZZBc            Toni Hofreiter auf dem 44. Bundesparteitag der Grünen in Bielefeld 2019 – Bewerbungsrede
        QO_Y14cx8Lo                               Jamila Schäfer | Einbringung International zusammenarbeiten | #dBDK21
        _cfV76TxsY8           Christian Meyer auf dem 44. Bundesparteitag der Grünen in Bielefeld 2019 – Bewerbungsrede
        YjN_Q4JIQjw                                              Steffi Lemke | Rede auf dem Parteitag in Bonn | #BDK22
FDP     UYtJ1msQuYM                                             Die Union darf sich von der SPD nicht erpressen lassen!
        pdlIAFuKRQI                                                     Zur Wahl des Ministerpräsidenten in #Thüringen.
        4yJCimj2O_U                                                   Michael Theurer bei der Dreikönigskundgebung 2018
        exvX1gSRtD0                                      Wir wollen einen Zertifikatehandel, der diesen Namen verdient!
        TbTJccB-Up8                                                                              #Migration und #Corona
        QICTmpFHwmQ                                                          Staat ist größter Kostentreiber bei Mieten
        Ie6tihXg7A4                           Mehr vom Falschen wird der SPD nicht helfen und würde Deutschland schaden
        6n0TgxBjWuc                                                        Keine höherer Belastung mit der FDP | #BTW21
        rDZdmV-4DgI                                                       Hans Ulrich Rülke beim Dreikönigstreffen 2018
        1ze5fpz3oFE                                 "Europa muss seine Chancen nutzen" - Best-of Nicola Beer vom #BPT19
CSU     toVAryo-KIA                                                                   Fail des Tages | "Danke, Antifa!"
        nDYYxXPqXGQ                                          CSU pur beim Politischen Aschermittwoch in Passau #CSUAM23
        N431nIgfOnA   Pressestatement von CSU-Chef und Ministerpräsident Markus Söder zur politischen Lage in Thüringen
        K0HX5OUY1cQ                                               Fail des Tages I Öffentliches Gelöbnis der Bundeswehr
        iPKZDFAdIYs                                                                    #fragCSU - Nein zu Enteignungen!
        983lQr9XElg                                         Unsere Ehrenvorsitzenden zur Richtungswahl am 26. September
        16jEAhKmF-I                                 Die Schlusskundgebung in München - Damit Deutschland stabil bleibt!
        6eSiwakBcgY                                                                  Richtungsentscheidung für Soldaten
        pJVOIfs3h-k                                                       Das war der Europa-Parteitag 2019 in Nürnberg
        -YMkFuGjPr4         Alexander Dobrindt spricht Klartext zur Richtungswahl 2021: Starke Mitte oder linkes Chaos?
CDU     EksM0bVVH1M                        Statement des Generalsekretärs zur Wahl des Ministerpräsidenten in Thüringen
        bbcjzNNtveo                                                                      Kandidatur Dr. Stefan Heck MdB
        xgkXD9s4Opc                                                               Unsere Haltung zu Linkspartei und AfD
        oYAl63O10gU                                                    Paul Ziemiak berichtet aus der Präsidiumssitzung
        6_RMW7sF4kM                                        CDU-Bundesausschuss: Freiheit verteidigen. Chancen eröffnen.
        t9oeOo08rGM             Grußwort von Daniel Caspary, Vorsitzender der CDU/CSU-Gruppe im Europäischen Parlament.
        q64peGPwHV8                                 #Deutschlandreise: Das Reisetagebuch. 21. September 2021: Stralsund
        GfIbnaLOS7M                                                       Starker Auftritt von Armin Laschet im #Triell
        mINqf00pBts                                              Solide Finanzen und nachhaltige Politik - Paul Ziemiak
        lxNdOTGa3-I                                                      CDU Live mit Helge Braun – Die Zusammenfassung
AfD TV  wtAo1hE9pEc                                   Heizungsgesetz: Die Ampel macht Politik gegen 80 % der Deutschen!
        gbz_LecnBGs                          Die Welt lacht sich kaputt über Deutschland – und nimmt uns genüsslich aus
        NZYZJ85lE2I                             Kein Bonus für ungeimpfte Pfleger? AfD rechnet mit Mobbing-Koalition ab
        XdKfTJZeuec                                                         ❝Hände weg von unserer Automobilindustrie!❞
        3W20MPRKKiM                                    Heizhammer im Bundestag - wir sagen: Schluss mit dem Klima-Joch!
        c26W8Kr-3pE                                            Klimatyrannen versetzen Menschen in Angst und Schrecken!
        W-gBgUkLHAI                                                                     Alice Weidel ZERLEGT die Ampel!
        xHA4qgJFXuw                                                     Tino Chrupalla zur Halbzeit der Ampel-Regierung
        Kz0pA-d8yik                                                       Hilse: Bedient Euch endlich Eures Verstandes!
        -FNThb9JO-w                                                 Jörg Meuthen liest Ursula von der Leyen die Leviten
AfD BT  bfjB_0uTBAo       Die nationale Souveränität darf nicht gefährdet werden! - Norbert Kleinwächter - AfD-Fraktion
        lTU0Ojmf67o                  Alice Weidel rechnet mit der neuen Ampel-Regierung ab! - AfD-Fraktion im Bundestag
        VNZxUu862RQ           Von der Leyen, die unfähigste Kommissionspräsidentin! - Beatrix von Storch - AfD-Fraktion
        W8xf0eEvVQE  Totalversagen: Herr Lauterbach, legen Sie endlich Ihr Amt nieder! - Martin Sichert -  AfD-Fraktion
        uYIlmYDoy1M             Windenergie: Sie halten das Volk extra in Angst! Karsten Hilse - AfD-Fraktion Bundestag
        _p9AyHJTzuw     Umweltaktivisten schaffen Umwelt- und Artenschutz ab! - Thomas Ehrhorn - AfD-Fraktion Bundestag
        mGLBCRcFQyE   🚦Sie brechen vorsätzlich Recht! Martin Sichert rechnet mit der Ampel ab! - AfD-Fraktion Bundestag
        otnmHzXujZQ             EU-Scheinkompromisse zu Lasten Deutschlands! - Harald Weyel - AfD-Fraktion im Bundestag
        Z5HES8fziQo                         Nein zur grünen Klima-Diktatur! - Karsten Hilse - AfD-Fraktion im Bundestag
        zbWzxoJklmg                             "Wir trauen Ihnen nicht!" - Christian Wirth - AfD-Fraktion im Bundestag

                     n_sentences     elite  pplcentr  quantile  top_1p
channel video_id
SPD     F0c4_NPpnGA           57  0.263158  0.122807  0.144285       1
        d6vy8DvlA6k           20  0.250000  0.000000  0.144285       1
        2eJPpGsTI0c            6  0.166667  0.000000  0.144285       1
        2rwXzpbyDEU           12  0.166667  0.000000  0.144285       1
        y1WnueSc9fQ           26  0.153846  0.000000  0.144285       1
        3HwEQBSzMUI           93  0.139785  0.075269  0.144285       0
        B4hGX4jIMks           15  0.133333  0.066667  0.144285       0
        CtIAZCMJyWg           30  0.133333  0.033333  0.144285       0
        nuVHZu54xvU            8  0.125000  0.000000  0.144285       0
        67wvrzYddRo            8  0.125000  0.125000  0.144285       0
Left    l5abgjJlcE4           27  0.518519  0.111111  0.444605       1
        MUgDgKGu5Bg           10  0.500000  0.000000  0.444605       1
        9DC619q6mVA            6  0.500000  0.166667  0.444605       1
        FFg9z4i9lqM            6  0.500000  0.000000  0.444605       1
        35yCb1A9bmc           38  0.447368  0.026316  0.444605       1
        GSfgp8r9h3A           16  0.437500  0.062500  0.444605       0
        s15ADZa3BvI           40  0.375000  0.200000  0.444605       0
        L3wllg-iZNg           12  0.333333  0.166667  0.444605       0
        zN5YQIN5ep8           16  0.312500  0.000000  0.444605       0
        quIkOTiaCSA           13  0.307692  0.076923  0.444605       0
Greens  BKA5Rs9r7WE           29  0.310345  0.103448  0.226367       1
        iM80OK5_e9E           22  0.272727  0.090909  0.226367       1
        sTFRFy4jcN4            8  0.250000  0.125000  0.226367       1
        fvgOxVAw5hQ           39  0.230769  0.076923  0.226367       1
        kMlQJQjV__M           35  0.228571  0.000000  0.226367       1
        5aAfx-1usQ0           49  0.224490  0.020408  0.226367       0
        neJCKmYZZBc           23  0.217391  0.043478  0.226367       0
        QO_Y14cx8Lo           44  0.204545  0.045455  0.226367       0
        _cfV76TxsY8           44  0.204545  0.090909  0.226367       0
        YjN_Q4JIQjw           60  0.200000  0.033333  0.226367       0
FDP     UYtJ1msQuYM           19  0.263158  0.052632  0.214286       1
        pdlIAFuKRQI           40  0.250000  0.000000  0.214286       1
        4yJCimj2O_U          123  0.235772  0.048780  0.214286       1
        exvX1gSRtD0           23  0.217391  0.000000  0.214286       1
        TbTJccB-Up8           14  0.214286  0.000000  0.214286       0
        QICTmpFHwmQ           14  0.214286  0.000000  0.214286       0
        Ie6tihXg7A4           40  0.200000  0.000000  0.214286       0
        6n0TgxBjWuc           26  0.192308  0.038462  0.214286       0
        rDZdmV-4DgI          125  0.192000  0.024000  0.214286       0
        1ze5fpz3oFE           22  0.181818  0.045455  0.214286       0
CSU     toVAryo-KIA           14  0.285714  0.071429  0.238889       1
        nDYYxXPqXGQ           24  0.250000  0.000000  0.238889       1
        N431nIgfOnA           18  0.222222  0.000000  0.238889       0
        K0HX5OUY1cQ           10  0.200000  0.100000  0.238889       0
        iPKZDFAdIYs           26  0.192308  0.000000  0.238889       0
        983lQr9XElg           22  0.181818  0.000000  0.238889       0
        16jEAhKmF-I           11  0.181818  0.181818  0.238889       0
        6eSiwakBcgY           12  0.166667  0.000000  0.238889       0
        pJVOIfs3h-k           12  0.166667  0.000000  0.238889       0
        -YMkFuGjPr4           19  0.157895  0.000000  0.238889       0
CDU     EksM0bVVH1M            8  0.375000  0.000000  0.142857       1
        bbcjzNNtveo           10  0.300000  0.000000  0.142857       1
        xgkXD9s4Opc           22  0.272727  0.000000  0.142857       1
        oYAl63O10gU           43  0.209302  0.000000  0.142857       1
        6_RMW7sF4kM           12  0.166667  0.000000  0.142857       1
        t9oeOo08rGM           25  0.160000  0.000000  0.142857       1
        q64peGPwHV8           14  0.142857  0.000000  0.142857       0
        GfIbnaLOS7M           56  0.142857  0.035714  0.142857       0
        mINqf00pBts            7  0.142857  0.000000  0.142857       0
        lxNdOTGa3-I            7  0.142857  0.285714  0.142857       0
AfD TV  wtAo1hE9pEc           12  0.750000  0.000000  0.571429       1
        gbz_LecnBGs           19  0.736842  0.157895  0.571429       1
        NZYZJ85lE2I           25  0.680000  0.040000  0.571429       1
        XdKfTJZeuec            9  0.666667  0.000000  0.571429       1
        3W20MPRKKiM           24  0.666667  0.000000  0.571429       1
        c26W8Kr-3pE           24  0.666667  0.000000  0.571429       1
        W-gBgUkLHAI           59  0.661017  0.033898  0.571429       1
        xHA4qgJFXuw            8  0.625000  0.125000  0.571429       1
        Kz0pA-d8yik           15  0.600000  0.066667  0.571429       1
        -FNThb9JO-w           17  0.588235  0.000000  0.571429       1
AfD BT  bfjB_0uTBAo           17  0.705882  0.000000  0.528024       1

In [14]:
top_videos.reset_index()[["channel", "n_sentences", "elite", "video_title"]].to_csv(
    src.OUT / "tables/most_antielitism_videos_per_channel.csv",
    index=False,
)