In [6]:
import ibis

import src

In [11]:
import pandas as pd

pd.set_option("display.max_colwidth", None)

In [20]:
transcripts_path = src.PATH / "data/interim/transcripts/v3_large_turbo.duckdb"
sentences_path = src.PATH / "data/interim/sentences.parquet"

con = ibis.connect(f"duckdb://{transcripts_path}")
sentences = con.read_parquet(sentences_path)

transcripts = con.table("transcripts")

In [ ]:
sentences.filter(sentences.video_id == "KhUua9MFqj8").order_by(sentences.sentence_no)

In [ ]:
transcripts.filter(transcripts.video_id == "6OunlqOGTRE").to_pandas()

      video_id  \
0  6OunlqOGTRE


In [17]:
transcripts.filter(transcripts.video_id == "KhUua9MFqj8").to_pandas()

      video_id  \
0  KhUua9MFqj8


In [5]:
transcripts.to_parquet(src.PATH / "data/interim/transcripts/v3_large_turbo.parquet")